# Generated by Django 5.2 on 2025-04-24 00:59

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='atlas_password',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='atlas_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='ranger_password',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='ranger_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
