# Generated by Django 5.2 on 2025-04-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_credentials_atlas_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='atlas_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='ranger_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
