# Generated by Django 5.2 on 2025-04-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('new_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_file', to='core.file')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_file', to='core.file')),
            ],
        ),
    ]
