# Generated by Django 5.2 on 2025-05-01 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileaction_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='atlas_entity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AnnotationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=100)),
                ('missing_percentage', models.FloatField(blank=True, null=True)),
                ('is_outlier_present', models.BooleanField(default=False)),
                ('suggested_type', models.CharField(blank=True, max_length=100, null=True)),
                ('normalization', models.CharField(blank=True, max_length=100, null=True)),
                ('pattern_detected', models.JSONField(default=list)),
                ('semantic_cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.file')),
            ],
            options={
                'unique_together': {('file', 'column_name')},
            },
        ),
        migrations.CreateModel(
            name='ColumnAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.annotationcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='core.metadata')),
            ],
            options={
                'unique_together': {('metadata', 'user')},
            },
        ),
    ]
