# Generated by Django 5.2 on 2025-05-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='atlas_entity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=100)),
                ('missing_percentage', models.FloatField(blank=True, null=True)),
                ('is_outlier_present', models.BooleanField(default=False)),
                ('suggested_type', models.CharField(blank=True, max_length=100, null=True)),
                ('normalization', models.CharField(blank=True, max_length=100, null=True)),
                ('pattern_detected', models.JSONField(default=list)),
                ('semantic_cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.file')),
            ],
            options={
                'unique_together': {('file', 'column_name')},
            },
        ),
    ]
