# Generated by Django 5.2 on 2025-05-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_delete_metadataentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivecolumn',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
