# Generated by Django 5.2 on 2025-05-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_hivecolumn_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivecolumn',
            name='classifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hivetable',
            name='classifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hivetable',
            name='retention_period',
            field=models.IntegerField(blank=True, help_text='Retention in days', null=True),
        ),
    ]
