# Generated by Django 5.2 on 2025-05-29 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_hivecolumn_classifications_hivetable_classifications_and_more'),
        ('users', '0012_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_guid', models.CharField(max_length=100, unique=True)),
                ('display_text', models.CharField(max_length=255)),
                ('glossary_name', models.CharField(max_length=255)),
                ('glossary_guid', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='users.team')),
            ],
        ),
    ]
