# Generated by Django 5.2 on 2025-04-10 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_firstname_user_lastname_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
