# Generated by Django 5.2 on 2025-05-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_team_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
