# Generated by Django 5.2 on 2025-05-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_last_login_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='data_domains',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', to='users.datadomain'),
        ),
    ]
