# Generated by Django 5.2 on 2025-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_datadomain_user_data_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_domains',
            field=models.ManyToManyField(blank=True, related_name='owners', to='users.datadomain'),
        ),
    ]
