# Generated by Django 5.2 on 2025-05-01 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_data_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadomain',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_domains', to='users.team'),
        ),
        migrations.AlterField(
            model_name='datadomain',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='datadomain',
            unique_together={('name', 'team')},
        ),
    ]
