# Generated by Django 5.2 on 2025-05-03 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_guid', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_name', models.CharField(max_length=255)),
                ('term_guid', models.CharField(max_length=100)),
                ('term_name', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('proposed_changes', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AtlasDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('hive_db', 'Hive Database'), ('hive_table', 'Hive Table'), ('hive_column', 'Hive Column'), ('glossary', 'Glossary')], max_length=20)),
                ('parent_guid', models.CharField(blank=True, max_length=100, null=True)),
                ('guid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('qualified_name', models.CharField(max_length=255)),
                ('raw_data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_changed', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['data_type'], name='atlasHive_a_data_ty_47c6ad_idx'), models.Index(fields=['parent_guid'], name='atlasHive_a_parent__cd92c3_idx')],
                'unique_together': {('user', 'guid')},
            },
        ),
    ]
