# Generated by Django 5.2 on 2025-05-02 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_file_atlas_entity_name_annotationcategory_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100, unique=True)),
                ('type_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('qualified_name', models.CharField(max_length=255)),
                ('raw_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PendingAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('proposed_changes', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.annotationcategory')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlasHive.atlasentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('entity', 'user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ApprovedAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('atlas_sync_status', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_annotations', to=settings.AUTH_USER_MODEL)),
                ('original_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atlasHive.pendingannotation')),
            ],
        ),
    ]
