# Generated by Django 5.2 on 2025-05-03 21:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlasHive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='atlasdatacache',
            name='atlasHive_a_parent__cd92c3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='atlasdatacache',
            unique_together={('user', 'data_type')},
        ),
        migrations.RemoveField(
            model_name='atlasdatacache',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='atlasdatacache',
            name='parent_guid',
        ),
    ]
