# Generated by Django 5.2 on 2025-05-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlasHive', '0003_personalglossary_personalglossaryterm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='entity_guid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='entity_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='entity_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='term_guid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='term_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalannotation',
            name='entity_guid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalannotation',
            name='entity_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalannotation',
            name='entity_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
